In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3]) # создание numpy массива из обычного
zeros = np.zeros((2, 3)) # Матрица 2 на 3, заполненная нулями
ones = np.ones((2, 3)) # Матрица 2 на 3, заполненная единицими
arr2 = np.arange(10, 51, 10) # Создает последовательность [10; 51) с шагом 10
print(zeros.shape) # Вывод формы матрицы zeros
print(zeros.dtype) # Вывод типа данных, хранимых в zeros

print(arr1 + ones) # Поэлементное сложение
print(arr1.mean()) # Средняя величина

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
float64
[[2. 3. 4.]
 [2. 3. 4.]]
2.0
